/* eslint-disable */
export const memory: WebAssembly.Memory;
export function is_chinese(a: number): number;
export function is_japanese(a: number): number;
export function is_korean(a: number): number;
export function is_cjk(a: number): number;
export function is_number_forms(a: number): number;
export function is_cjk_compatibility_forms(a: number): number;
export function is_enclosed_cjk_letters_and_months(a: number): number;
export function is_latin1_supplement(a: number): number;
export function is_greek_and_coptic(a: number): number;
export function is_enclosed_alphanumerics(a: number): number;
export function is_cjk_compatibility(a: number): number;
export function is_common_symbols(a: number): number;
export function is_open_parentheses(a: number): number;
export function is_close_parentheses(a: number): number;
export function is_western_sentence_punctuation(a: number): number;
export function is_colon(a: number): number;
export function is_quote(a: number): number;
export function __wbg_get_spacingoptions_punctuations(a: number): number;
export function __wbg_set_spacingoptions_punctuations(a: number, b: number): void;
export function __wbg_options_free(a: number): void;
export function __wbg_get_options_spacing(a: number): number;
export function __wbg_set_options_spacing(a: number, b: number): void;
export function get_char_type(a: number): number;
export function format(a: number, b: number, c: number, d: number): void;
export function __wbg_spacingoptions_free(a: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_export_0(a: number, b: number): number;
export function __wbindgen_export_1(a: number, b: number, c: number, d: number): number;
export function __wbindgen_export_2(a: number, b: number, c: number): void;
